### PR TITLE
dummy commit

### PR DESCRIPTION
**Pull request by tillmo**
when compiling #1941 rebased on master, I get
```
[661 of 868] Compiling GUI.GtkUtils     ( GUI/GtkUtils.hs, GUI/GtkUtils.o )

GUI/GtkUtils.hs:549:3: error:
    • No instance for (TreeModelClass (Maybe (ListStore a)))
        arising from a use of ‘treeViewSetModel’
    • In a stmt of a 'do' block: treeViewSetModel view (Just store)
      In the expression:
        do { store <- listStoreNew listData;
             treeViewSetModel view (Just store);
             treeViewSetHeadersVisible view False;
             ren <- cellRendererTextNew;
             .... }
      In an equation for ‘setListData’:
          setListData view getT listData
            = do { store <- listStoreNew listData;
                   treeViewSetModel view (Just store);
                   treeViewSetHeadersVisible view False;
                   .... }
```
This PR is for checking whether this may be caused by commits on the master branch.

### CODE REVIEW

**Comment by TpmKranz** [comment]
The signature change for `treeViewSetModel` was introduced in https://github.com/gtk2hs/gtk2hs/commit/b1f3bbe9f366a841777911fefba3bcdd4bb76128, leading me to believe you have a `gtk` version < 0.15 in your environment. Did you `make restack` after pulling the most recent master? #1939 introduced `gtk-0.15.5` as one of the `extra-deps`.

**Comment by tillmo** [comment]
you are right, that was an old error that I could indeed solve with `make resrack`. I mixed things up.
The problem I want to tackle is that travis fails here: https://travis-ci.com/github/spechub/Hets/jobs/394044573

**Comment by tillmo** [comment]
OK, f4ac445efe27b1d7cccfdd275715d33b74a744be (the current master) works. Now trying 43ee7ac001f5b116d3701979931c330aff883aa5

**Comment by tillmo** [comment]
43ee7ac works. Now trying 28e56b0b6

**Comment by tillmo** [comment]
Indeed, 28e56b0 failed - but why? Only two make targets have been renamed. Do they appear in the travis scripts?

**Comment by tillmo** [comment]
The error is in the 5th travis job:
```
*** Error:

OWL2Parser.jar not found, check your environment variable: HETS_OWL_TOOLS

for Hets usage, use: hets -h

The command "test/hets-lib-check.sh" exited with 2.
```
Why is this related to 28e56b0 ?

**Comment by tillmo** [comment]
Now trying 0200519b9, which is the same as PR #1942, just to see whether the results are the same.

**Comment by tillmo** [comment]
Aha, need a dummy commit 8a1e0c2290381d83a5683639559a26efc7192512 - otherwise travis is not run again.

**Comment by tillmo** [comment]
aha, this one has passed. So 0200519 should also pass, because the difference is only in `README.md`. It is problematic that travis results are not reproducible.

**Comment by tillmo** [comment]
was for testing if travis works - not needed anymore
